-- migrations/1.1.0/002_add_template_extraction.sql
-- Description: Add template extraction metadata to Template model
-- Version: 1.1.0
-- Date: 2024-12-10
-- Phase: 2 - Template Extraction Feature

-- Add sourceUrl column (stores the URL from which template was extracted)
-- Used by the Puppeteer-based template scraper service
ALTER TABLE Template ADD COLUMN sourceUrl TEXT;

-- Add extractionMethod column (stores the method used to extract template)
-- Values: 'manual', 'puppeteer', 'ai-assisted'
ALTER TABLE Template ADD COLUMN extractionMethod TEXT;

-- Add layoutMetadata column (stores extracted layout information)
-- Format: JSON with structure:
-- {
--   gridSystem: 'css-grid' | 'flexbox' | 'float',
--   columns: { count: number, widths: string[] },
--   typography: { fonts: string[], sizes: {...} },
--   colors: { primary: string, accent: string, ... },
--   breakpoints: { mobile: number, tablet: number, desktop: number },
--   hasSidebar: boolean,
--   sidebarPosition: 'left' | 'right',
--   ...
-- }
ALTER TABLE Template ADD COLUMN layoutMetadata TEXT;

-- Add previewImage column (stores base64 or URL of template screenshot)
-- Generated by Puppeteer during extraction for visual preview
ALTER TABLE Template ADD COLUMN previewImage TEXT;

-- Note: These columns support the Phase 2 template extraction feature
-- The extraction process uses Puppeteer to:
-- 1. Navigate to sourceUrl
-- 2. Extract computed CSS styles
-- 3. Analyze HTML structure
-- 4. Generate layoutMetadata
-- 5. Capture screenshot as previewImage
-- 6. Store extraction method used
